//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Management.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOG_MAIN                 102
#define IDS_FILE_FILTER                 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_QUESTION             129
#define IDD_DIALOG_LOGIN                130
#define IDD_DIALOG_ADDANDEDIT           132
#define IDB_BITMAP_BEGIN                133
#define IDD_DIALOG_PAPER                142
#define IDB_TREE1                       143
#define IDD_DIALOG_AUTO                 146
#define IDD_DIALOG_SAVEEXIST            149
#define IDD_DIALOG_SELCHAPANDDIFF       150
#define IDD_DIALOG_SELQUES              152
#define IDD_DIALOG_PERSON               154
#define IDB_BITMAP2                     164
#define IDB_BITMAP4                     166
#define IDB_BITMAP_HELP                 167
#define IDB_BITMAP_ABOUT                168
#define IDD_DIALOG_MANAGE               169
#define IDB_BITMAP_PAPER                170
#define IDB_BITMAP_QUES                 171
#define IDB_BITMAP_BACK                 172
#define IDD_DIALOG_PASSWORD             173
#define IDD_DIALOG_MANAGEPAPER          174
#define IDD_DIALOG_BROWSE               175
#define IDD_DIALOG_EDITANSWER           176
#define IDD_DIALOG_MANAGEPOOL           177
#define IDD_DIALOG_MANAGETYPE           178
#define IDD_DIALOG_BROWSWALL            180
#define IDD_DIALOG_IMPORT               185
#define IDD_DIALOG_SELRES               186
#define IDC_BUTTON_MANAGE               1003
#define IDC_BUTTON_QUESTION             1003
#define IDC_BUTTON_TEXT                 1004
#define IDC_BUTTON_PAPER                1004
#define IDC_EDIT_CONTENT                1011
#define IDC_EDIT_PASSWORD               1012
#define IDC_EDIT_ANSWER                 1012
#define IDC_EDIT_USERNAME               1013
#define IDC_EDIT_ID                     1015
#define IDC_EDIT_TYPE                   1016
#define IDC_EDIT_DIFFICULTY             1017
#define IDC_EDIT_CHAPTER                1018
#define IDC_BUTTON_FIRST                1019
#define IDC_BUTTON_PRE                  1021
#define IDC_BUTTON_NEXT                 1022
#define IDC_BUTTON_LAST                 1023
#define IDC_BUTTON_EDIT                 1024
#define IDC_BUTTON_DELETE               1025
#define IDC_BUTTON_ADD                  1026
#define IDC_LIST_QUESTION               1027
#define IDC_BUTTON_CLEAR                1028
#define IDC_COMBO_SUBJECT               1029
#define IDC_BUTTON_CONFIRM              1031
#define IDC_BUTTON_ADDTABLE             1032
#define IDC_BUTTON_CLOSE                1033
#define IDC_COMBO1                      1034
#define IDC_COMBO_TYPE                  1034
#define IDC_COMBO_NUMBER                1034
#define IDC_COMBO_CREATEPERSON          1034
#define IDC_COMBO_PURVIEW               1034
#define IDC_COMBO2                      1035
#define IDC_COMBO_DIFFICULTY            1035
#define IDC_COMBO_NO1                   1035
#define IDC_COMBO3                      1036
#define IDC_COMBO_CHAPTER               1036
#define IDC_COMBO_NO2                   1036
#define IDC_COMBO_NO3                   1037
#define IDC_BUTTON_QUERY                1038
#define IDC_COMBO_NO4                   1038
#define IDC_EDIT_NEWTYPE                1039
#define IDC_COMBO_NO5                   1039
#define IDC_EDIT_NEWSUBJECT             1040
#define IDC_COMBO_NO6                   1040
#define IDC_TREE_ALL                    1041
#define IDC_COMBO_NO7                   1041
#define IDC_COMBO_NO8                   1042
#define IDC_COMBO_NO9                   1043
#define IDC_COMBO_NO10                  1044
#define IDC_BUTTON_IN                   1052
#define IDC_BUTTON_OUT                  1053
#define IDC_EDIT_QUERYID                1054
#define IDC_BUTTON_PERSON               1054
#define IDC_BUTTON_QUERYONLY            1055
#define IDC_BUTTON_INANSWER             1055
#define IDC_BUTTON_ONLYQUERY            1056
#define IDC_STATIC_TITLE                1057
#define IDC_STATIC_TITLEPAPER           1058
#define IDC_BUTTON_START                1062
#define IDC_EDIT_SCORE1                 1065
#define IDC_EDIT_SCORE2                 1066
#define IDC_EDIT_SCORE3                 1067
#define IDC_EDIT_SCORE4                 1068
#define IDC_EDIT_SCORE5                 1069
#define IDC_EDIT_SCORE6                 1070
#define IDC_EDIT_SCORE7                 1071
#define IDC_EDIT_SCORE8                 1072
#define IDC_EDIT_COUNT1                 1073
#define IDC_EDIT_COUNT2                 1074
#define IDC_EDIT_COUNT3                 1075
#define IDC_EDIT_COUNT4                 1076
#define IDC_EDIT_COUNT5                 1077
#define IDC_EDIT_COUNT6                 1078
#define IDC_EDIT_COUNT7                 1079
#define IDC_EDIT_COUNT8                 1080
#define IDC_EDIT_SCORE9                 1081
#define IDC_EDIT_COUNT9                 1082
#define IDC_EDIT_SCORE10                1083
#define IDC_EDIT_COUNT10                1084
#define IDC_EDIT_PAPER                  1085
#define IDC_BUTTON_OTHER1               1086
#define IDC_BUTTON_OTHER2               1087
#define IDC_BUTTON_OTHER3               1088
#define IDC_BUTTON_OTHER4               1089
#define IDC_BUTTON_OTHER5               1090
#define IDC_BUTTON_OTHER6               1091
#define IDC_BUTTON_OTHER7               1092
#define IDC_BUTTON_OTHER8               1093
#define IDC_BUTTON_OTHER9               1094
#define IDC_BUTTON_OTHER10              1095
#define IDC_BUTTON_AUTO                 1101
#define IDC_BUTTON_SELECT               1114
#define IDC_BUTTON_RESET                1115
#define IDC_LIST_SELECT                 1115
#define IDC_BUTTON_OUTANSWER            1118
#define IDC_BUTTON_LOGIN                1128
#define IDC_BUTTON_POOL                 1136
#define IDC_BUTTON_BROWSE               1137
#define IDC_BUTTON_MANAGEPAPER          1138
#define IDC_BUTTON_PASSWORD             1139
#define IDC_EDIT_NEW                    1140
#define IDC_LIST_PAPER                  1141
#define IDC_EDIT_OLD                    1141
#define IDC_EDIT_NEWAGAIN               1142
#define IDC_DATETIMEPICKER_FROM         1145
#define IDC_DATETIMEPICKER_TO           1146
#define IDC_TREE_PAPER                  1150
#define IDC_CHECK_DATE                  1153
#define IDC_BUTTON_EDITANSWER           1154
#define IDC_LIST_POOL                   1159
#define IDC_EDIT_SUBJECT                1160
#define IDC_BUTTON_MANAGETYPE           1164
#define IDC_LIST_TYPE                   1165
#define IDC_BUTTON_OUTPAPER             1167
#define IDC_STATIC_PAPER                1169
#define IDC_STATIC_ANSWER               1170
#define IDC_DATETIMEPICKER_CREATE       1170
#define IDC_TREE_CHAPTER                1172
#define IDC_STATIC_TYPEEXIST            1179
#define IDC_STATIC_EASY                 1180
#define IDC_STATIC_EASIER               1181
#define IDC_STATIC_MID                  1182
#define IDC_STATIC_HARDER               1183
#define IDC_STATIC_HARD                 1184
#define IDC_STATIC_DIFFALL              1185
#define IDC_STATIC_TYPESEL              1186
#define IDC_EDIT_EASY                   1187
#define IDC_EDIT_EASIER                 1188
#define IDC_EDIT_MID                    1189
#define IDC_EDIT_HARDER                 1190
#define IDC_EDIT_HARD                   1191
#define IDC_SPIN_EASY                   1194
#define IDC_EDIT_SCORE                  1195
#define IDC_SPIN_EASIER                 1197
#define IDC_STATIC_NUM                  1197
#define IDC_SPIN_MID                    1198
#define IDC_SPIN_HARDER                 1199
#define IDC_SPIN_HARD                   1200
#define IDC_STATIC_SELALL               1201
#define IDC_EDIT_FILE                   1202
#define IDC_RADIO1                      1204
#define IDC_RADIO2                      1205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1205
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
